### ISSUE TITLE
ERD

### ISSUE THREAD

**Issue by f-z-d** [Ne0kropolis/ReservationApplication#1]

**Comment by f-z-d** [comment]
https://drive.google.com/file/d/1PZqkMdRnNbckXMzSaErNo-Cf1rRc6YoB/view?usp=sharing

**Comment by Ernst95** [comment]
Hi @Ne0kropolis 

I don't think we need the agentCode and status in the Agent entity. We can just create a UserType entity that specifies the type of user the person is and link it with the userType field that  you have in the User entity. We can then move status to the User entity to identify if they are active or inactive. 

Then in the Property entity we can use the userID instead of agentCode.

That's just my thoughts let me know if I maybe misinterpreted the ERD, other than that everything looks good.
